import type { AttractionWait } from "./types";

export const mockAttractionWaits: AttractionWait[] = [
  // Disneyland Park attractions
  {
    id: "dl-space-mountain",
    name: "Space Mountain",
    parkId: "DL",
    waitTime: 45,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dl-space-mountain",
  },
  {
    id: "dl-matterhorn",
    name: "Matterhorn Bobsleds",
    parkId: "DL",
    waitTime: 35,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dl-matterhorn-bobsleds",
  },
  {
    id: "dl-big-thunder",
    name: "Big Thunder Mountain Railroad",
    parkId: "DL",
    waitTime: 40,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dl-big-thunder-mountain",
  },
  {
    id: "dl-splash-mountain",
    name: "Splash Mountain",
    parkId: "DL",
    waitTime: 55,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dl-splash-mountain",
  },
  {
    id: "dl-indiana-jones",
    name: "Indiana Jones Adventure",
    parkId: "DL",
    waitTime: 60,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dl-indiana-jones",
  },
  {
    id: "dl-pirates",
    name: "Pirates of the Caribbean",
    parkId: "DL",
    waitTime: 25,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dl-pirates-of-the-caribbean",
  },
  {
    id: "dl-haunted-mansion",
    name: "Haunted Mansion",
    parkId: "DL",
    waitTime: 30,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dl-haunted-mansion",
  },
  {
    id: "dl-star-tours",
    name: "Star Tours",
    parkId: "DL",
    waitTime: 20,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dl-star-tours",
  },

  // Disney California Adventure attractions
  {
    id: "dca-radiator-springs",
    name: "Radiator Springs Racers",
    parkId: "DCA",
    waitTime: 90,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dca-radiator-springs-racers",
  },
  {
    id: "dca-guardians",
    name: "Guardians of the Galaxy - Mission: BREAKOUT!",
    parkId: "DCA",
    waitTime: 50,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dca-guardians-of-the-galaxy",
  },
  {
    id: "dca-incredicoaster",
    name: "Incredicoaster",
    parkId: "DCA",
    waitTime: 45,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dca-incredicoaster",
  },
  {
    id: "dca-soarin",
    name: "Soarin' Around the World",
    parkId: "DCA",
    waitTime: 35,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dca-soarin-around-the-world",
  },
  {
    id: "dca-toy-story",
    name: "Toy Story Midway Mania!",
    parkId: "DCA",
    waitTime: 40,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dca-toy-story-midway-mania",
  },
  {
    id: "dca-grizzly-river",
    name: "Grizzly River Run",
    parkId: "DCA",
    waitTime: 30,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dca-grizzly-river-run",
  },
  {
    id: "dca-web-slingers",
    name: "WEB SLINGERS: A Spider-Man Adventure",
    parkId: "DCA",
    waitTime: 55,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dca-web-slingers",
  },
  {
    id: "dca-little-mermaid",
    name: "The Little Mermaid - Ariel's Undersea Adventure",
    parkId: "DCA",
    waitTime: 15,
    isOperational: true,
    lastUpdated: new Date().toISOString(),
    themeParksId: "TBD-dca-little-mermaid",
  },
];
